---
- name: install
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ install_packages }}"
  when: install_packages is defined

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ pip_packages }}"
  when: pip_packages is defined

- name: install app specific packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ install_app_packages }}"
  when: install_app_packages is defined

- name: install app specific pip packages
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ install_app_pip_packages }}"
  when: install_app_pip_packages is defined
